// Typelizer digest 5c6cd4f63f193af66f08b25f2e8851ce
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** PATCH /deliveries/:id */
  update: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'patch'> => ({
    url: buildUrl('/deliveries/:id', params, options),
    method: 'patch',
  }),
}
