// Typelizer digest 5e895b4e600a0e4b06ee2df35fd185e2
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
export { default as deliveries } from './DeliveriesController'
export { default as home } from './HomeController'

import _deliveries from './DeliveriesController'
import _home from './HomeController'

export const delivery = _deliveries.update
export const root = _home.index
