// Typelizer digest bbd8542dd8d513a2ba9b27cebd9eabbd
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Delivery = {
  id: number;
  order_id: number;
  status: string;
  address: string;
}

export type { Delivery };
