// Typelizer digest 862696a1f99ea72d23807819a5fec43c
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {StatusAction} from '@/types'

type Delivery = {
  id: number;
  order_id: number;
  status: string;
  address: string;
  actions: Array<StatusAction>;
}

export type { Delivery };
