// Typelizer digest 5fff4fce3eb4e7dd3baf0402c22e696f
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Delivery} from '@/types'

type HomeIndex = {
  deliveries: Array<Delivery>;
}

export type { HomeIndex };
